name: Maven build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        sed -i \"s/LIVE/${TRAVIS_BUILD_NUMBER}/g\" pom.xml
        mvn -q -B -s maven-settings.xml clean compile assembly:single deploy
